### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by rzashakeri** [barnamenevisi/roadmap#11]

**Comment by pariyaj** [comment]
![java](https://github.com/barnamenevisi/roadmap/assets/56969706/f1eae5d8-31fc-43d1-b099-af8615efb521)

**Comment by rzashakeri** [comment]
> ![java](https://private-user-images.githubusercontent.com/56969706/294696633-f1eae5d8-31fc-43d1-b099-af8615efb521.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTIzOTIsIm5iZiI6MTcwNDU1MjA5MiwicGF0aCI6Ii81Njk2OTcwNi8yOTQ2OTY2MzMtZjFlYWU1ZDgtMzFmYy00M2QxLWIwOTktYWY4NjE1ZWZiNTIxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0NDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmZmODBlN2VjMTBjNzMyYjVjNTYxYTEyNTA1ZjNmYmVhMDNlZGJhOGMwYzYyYWQyY2E4YzY5Y2M1ZDAyMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GaaXyJ4DCEZkAR-aO8XucINItBBIMWsrQtkDVXHQnYA)


سلام ممنونم بابت زمانی که گذاشتید
اگر با گیت آشنایی دارید pull request بدید 
اگر هم نه بگید من راهنماییتون کنم چون باید اسمتون داخل contributors بیاد به عنوان کسی که ترجمه کرده اینو

می‌تونید از آموزش زیر هم استفاده کنید :
https://vrgl.ir/dZwVL

**Comment by pariyaj** [comment]
ممنونم
