### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by rzashakeri** [barnamenevisi/roadmap#20]

**Comment by AmirAliAy** [comment]
![Web capture_11-1-2024_181458_roadmap sh](https://github.com/barnamenevisi/roadmap/assets/78584945/1b5a1402-5c45-41b4-8ad9-ea99f16cdd06)
ترجمه رو تمام کردم

**Comment by rzashakeri** [comment]
> ![Web capture_11-1-2024_181458_roadmap sh](https://private-user-images.githubusercontent.com/78584945/295952034-1b5a1402-5c45-41b4-8ad9-ea99f16cdd06.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODYxNjksIm5iZiI6MTcwNDk4NTg2OSwicGF0aCI6Ii83ODU4NDk0NS8yOTU5NTIwMzQtMWI1YTE0MDItNWM0NS00MWI0LThhZDktZWE5OWYxNmNkZDA2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNTExMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmQwYTQ3MGEzODQzYmNlZWEwZmI0YjNiYTg3ODZiYmE5MGE3Y2ZkZjAxMTE3ZDY5YmRmNTRmMmJmNjhlNDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Dd51sLiUtTu3o8Hiwbdc-IxYQRUNAnnnjO_qy1-V-w) ترجمه رو تمام کردم


سلام وقت به خیر
ممنونم بابت زمانی که گذاشتید، pull request بدید تا اضافه بشه
